[[redirects]]
  from = "/session"
  to = "https://github.com/sessions/two-factor/app"
  status = 302

[[redirects]]
  from = "/assets/*"
  to = "https://github.githubassets.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://github.com/:splat"
  status = 200

